# Exported from Render on 2026-05-02T19:56:17Z
version: "1"
projects:
  - name: Protectora de mascotas
    environments:
      - name: Production
        databases:
          - name: mascotas-pg
            databaseName: protectora_db_125o
            user: miguel_a_leiva
            plan: free
            region: frankfurt
            ipAllowList:
              - source: 0.0.0.0/0
                description: everywhere
            postgresMajorVersion: "18"
